# Generated by Django 3.1.5 on 2022-08-07 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolocalizaciones', '0002_auto_20220807_0052'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoacceso',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puntoacceso_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='puntoacceso',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sedes_empresa', to='gestiones.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='puntoacceso',
            name='horarios_acceso',
            field=models.ManyToManyField(blank=True, related_name='sedes_franja', to='gestiones.FranjaHoraria', verbose_name='Horarios de acceso'),
        ),
        migrations.AddField(
            model_name='puntoacceso',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puntoacceso_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='puntoacceso',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puntoacceso_removed_by', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
        migrations.AddField(
            model_name='franjahoraria',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franjahoraria_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='franjahoraria',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_empleado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='franjahoraria',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franjahoraria_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='franjahoraria',
            name='punto_acceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_sede', to='gestiones.puntoacceso', verbose_name='Punto de acceso'),
        ),
        migrations.AddField(
            model_name='franjahoraria',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franjahoraria_removed_by', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_administradas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas_ciudad', to='geolocalizaciones.ciudad'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='pais', chained_model_field='pais', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas_estado', to='geolocalizaciones.estado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_pais', to='geolocalizaciones.pais', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_removed_by', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
    ]
