# Generated by Django 3.1.5 on 2022-08-04 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestiones', '0001_initial'),
        ('geolocalizaciones', '0002_auto_20220804_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_administradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas_ciudad', to='geolocalizaciones.ciudad'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='pais', chained_model_field='pais', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas_estado', to='geolocalizaciones.estado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_pais', to='geolocalizaciones.pais', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_removed_by', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por'),
        ),
    ]
