# Generated by Django 3.1.5 on 2022-08-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0002_auto_20220807_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='pais_estado_ciudad',
            field=models.CharField(max_length=200, null=True, verbose_name='País, estado, ciudad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
    ]
