# Generated by Django 3.1.5 on 2022-08-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0002_auto_20220804_0418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='franjahoraria',
            options={'verbose_name': 'Franja horaria', 'verbose_name_plural': 'Franjas horarias'},
        ),
        migrations.AlterModelOptions(
            name='puntoacceso',
            options={'verbose_name': 'Punto de acceso', 'verbose_name_plural': 'Puntos de acceso'},
        ),
        migrations.AlterField(
            model_name='puntoacceso',
            name='horarios_acceso',
            field=models.ManyToManyField(blank=True, related_name='sedes_franja', to='gestiones.FranjaHoraria', verbose_name='Horarios de acceso'),
        ),
    ]
