# Generated by Django 3.1.5 on 2022-08-08 14:48

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalizaciones', '0003_auto_20220808_1044'),
        ('gestiones', '0003_auto_20220808_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ciudad',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas_ciudad', to='geolocalizaciones.ciudad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='pais', chained_model_field='pais', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas_estado', to='geolocalizaciones.estado'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_pais', to='geolocalizaciones.pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais_estado_ciudad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='País, estado, ciudad'),
        ),
    ]
