# Generated by Django 3.1.5 on 2022-08-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('abvr', models.CharField(blank=True, max_length=30, null=True, verbose_name='abreviatura')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('removed', models.BooleanField(default=False, verbose_name='eliminado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('creation_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de creación')),
                ('modification_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de modificación')),
                ('modification_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de modificación')),
                ('elimination_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('elimination_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de eliminación')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('abvr', models.CharField(blank=True, max_length=30, null=True, verbose_name='abreviatura')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('removed', models.BooleanField(default=False, verbose_name='eliminado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('creation_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de creación')),
                ('modification_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de modificación')),
                ('modification_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de modificación')),
                ('elimination_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('elimination_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de eliminación')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('abvr', models.CharField(blank=True, max_length=30, null=True, verbose_name='abreviatura')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('removed', models.BooleanField(default=False, verbose_name='eliminado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('creation_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de creación')),
                ('modification_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de modificación')),
                ('modification_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de modificación')),
                ('elimination_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('elimination_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de eliminación')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
    ]
