# Generated by Django 3.1.5 on 2022-08-03 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('abvr', models.CharField(blank=True, max_length=30, null=True, verbose_name='abreviatura')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('removed', models.BooleanField(default=False, verbose_name='eliminado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('creation_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de creación')),
                ('modification_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de modificación')),
                ('modification_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de modificación')),
                ('elimination_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('elimination_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de eliminación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_removed_by', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('abvr', models.CharField(blank=True, max_length=30, null=True, verbose_name='abreviatura')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('removed', models.BooleanField(default=False, verbose_name='eliminado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('creation_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de creación')),
                ('modification_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de modificación')),
                ('modification_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de modificación')),
                ('elimination_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('elimination_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de eliminación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados_pais', to='geolocalizaciones.pais', verbose_name='País')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_removed_by', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('abvr', models.CharField(blank=True, max_length=30, null=True, verbose_name='abreviatura')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('removed', models.BooleanField(default=False, verbose_name='eliminado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('creation_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de creación')),
                ('modification_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de modificación')),
                ('modification_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de modificación')),
                ('elimination_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('elimination_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip de eliminación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciudades_estado', to='geolocalizaciones.estado', verbose_name='Estado')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_removed_by', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
    ]
