# Generated by Django 3.1.5 on 2022-08-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pais_estado_ciudad',
            field=models.CharField(max_length=200, null=True, verbose_name='País, estado, ciudad'),
        ),
    ]
