# Generated by Django 3.1.5 on 2022-08-03 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe ingresarse en el formato: +999999999999. Se permiten hasta 15 dígitos.', regex='\\+?2?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe un usuario con ese email.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
